"use client";
import Link from "next/link";
import { useState } from "react";
import { useAdminTaxonomy, useCreateTaxonomy, useDeleteTaxonomy, useUpdateTaxonomy } from "@/features/posts/admin-hooks";
export default function TaxonomyPage() {
  const query = useAdminTaxonomy(); const create = useCreateTaxonomy(); const update = useUpdateTaxonomy(); const remove = useDeleteTaxonomy();
  const [name, setName] = useState(""); const [type, setType] = useState<"category" | "tag">("tag");
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim()) return; try { await create.mutateAsync({ type, data: { name: name.trim() } }); setName(""); } catch {} }
  async function edit(item: { id: string; name: string }, itemType: "category" | "tag") { const next = window.prompt("이름", item.name)?.trim(); if (!next || next === item.name) return; try { await update.mutateAsync({ type: itemType, id: item.id, data: { name: next } }); } catch {} }
  async function del(id: string, itemType: "category" | "tag") { if (!window.confirm("이 분류를 삭제할까요? 연결된 게시글의 분류도 제거됩니다.")) return; try { await remove.mutateAsync({ type: itemType, id }); } catch {} }
  const error = create.error ?? update.error ?? remove.error;
  return <main className="mx-auto max-w-4xl p-8"><div className="mb-8 flex justify-between"><h1 className="text-2xl font-semibold">카테고리 · 태그 관리</h1><Link href="/admin/posts" className="underline">게시글로 돌아가기</Link></div><form onSubmit={submit} className="mb-8 flex gap-2"><select value={type} onChange={(e) => setType(e.target.value as typeof type)} className="rounded border p-2"><option value="category">카테고리</option><option value="tag">태그</option></select><input value={name} onChange={(e) => setName(e.target.value)} placeholder="이름" className="rounded border p-2"/><button disabled={create.isPending} className="rounded bg-black px-4 py-2 text-white">추가</button></form>{error && <p role="alert" className="mb-4 text-red-600">{error.message}</p>}<div className="grid gap-8 md:grid-cols-2"><section><h2 className="mb-3 font-semibold">카테고리</h2><ul className="space-y-2">{query.data?.categories.map((item) => <li key={item.id} className="flex items-center justify-between rounded border p-3"><span>{item.name} <small className="text-slate-500">/{item.slug}</small></span><span className="flex gap-2"><button onClick={() => void edit(item, "category")} className="underline">수정</button><button onClick={() => void del(item.id, "category")} className="text-red-600 underline">삭제</button></span></li>)}</ul></section><section><h2 className="mb-3 font-semibold">태그</h2><ul className="space-y-2">{query.data?.tags.map((item) => <li key={item.id} className="flex items-center justify-between rounded border p-3"><span>#{item.name} <small className="text-slate-500">/{item.slug}</small></span><span className="flex gap-2"><button onClick={() => void edit(item, "tag")} className="underline">수정</button><button onClick={() => void del(item.id, "tag")} className="text-red-600 underline">삭제</button></span></li>)}</ul></section></div></main>;
}
